name: HPSI-Classification
channels:
  - menpo
  - defaults
dependencies:
  - alabaster=0.7.10=py35hb692fe1_0
  - appnope=0.1.0=py35hd172556_0
  - asn1crypto=0.24.0=py35_0
  - astroid=1.6.0=py35_0
  - babel=2.5.3=py35_0
  - bleach=2.1.2=py35_0
  - bokeh=0.12.13=py35h2f9c1c0_0
  - ca-certificates=2017.08.26=ha1e5d58_0
  - certifi=2017.11.5=py35hd00889a_0
  - cffi=1.11.4=py35h342bebf_0
  - chardet=3.0.4=py35h16a84c2_1
  - click=6.7=py35hcc65ea6_0
  - cloudpickle=0.5.2=py35h61e9bcc_0
  - cryptography=2.1.4=py35hbbb57dc_0
  - cycler=0.10.0=py35hb89929e_0
  - dask=0.16.1=py35_0
  - dask-core=0.16.1=py35_0
  - dbus=1.10.22=h50d9ad6_0
  - decorator=4.2.1=py35_0
  - distributed=1.20.2=py35_0
  - docutils=0.14=py35hb13dbd9_0
  - entrypoints=0.2.3=py35h837ec6f_2
  - expat=2.2.5=hb8e80ba_0
  - fastcache=1.0.2=py35h8aa0158_0
  - freetype=2.5.5=2
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.53.6=h33f6a65_2
  - gmp=6.1.2=hb37e062_1
  - gmpy2=2.0.8=py35h212fb8a_2
  - graphviz=2.38.0=4
  - h5py=2.7.1=py35h233cdc3_0
  - hdf5=1.8.18=h017327d_1
  - heapdict=1.0.0=py35h86051b3_0
  - html5lib=1.0.1=py35h2f9c1c0_0
  - icu=58.2=h4b95b61_1
  - idna=2.6=py35h01aacb0_1
  - imageio=2.2.0=py35h805106e_0
  - imagesize=0.7.1=py35h1ad78fc_0
  - intel-openmp=2018.0.0=h8158457_8
  - ipykernel=4.7.0=py35h2f9c1c0_0
  - ipython=6.2.1=py35h9470683_1
  - ipython_genutils=0.2.0=py35hf129286_0
  - isort=4.2.15=py35h0db285e_0
  - jedi=0.11.1=py35_0
  - jinja2=2.10=py35h6ff70ae_0
  - jpeg=9b=he5867d9_2
  - jsonschema=2.6.0=py35h2dd9e4b_0
  - jupyter_client=5.2.1=py35_0
  - jupyter_core=4.4.0=py35h4ad9194_0
  - keras=2.1.2=py35_0
  - lazy-object-proxy=1.3.1=py35h7293e74_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1=hb4e282d_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.32=hd1e8b91_4
  - libprotobuf=3.4.1=h326466f_0
  - libsodium=1.0.15=hd9e47c5_0
  - libtiff=4.0.9=h0dac147_0
  - locket=0.2.0=py35h58cf053_1
  - markupsafe=1.0=py35h9ba0a7f_1
  - matplotlib=2.0.2=np112py35_0
  - mccabe=0.6.1=py35h3f6a9a1_0
  - mistune=0.8.3=py35_0
  - mkl=2018.0.1=hfbd8650_4
  - mpc=1.0.3=h7a72875_5
  - mpfr=3.1.5=h711e7fd_2
  - mpmath=1.0.0=py35he743aed_2
  - msgpack-python=0.5.1=py35h04f5b5a_0
  - nbconvert=5.3.1=py35h63fb950_0
  - nbformat=4.4.0=py35h41c2038_0
  - ncurses=6.0=hd04f020_2
  - networkx=1.11=py35hd138405_0
  - numpy=1.12.1=py35h655160a_1
  - numpydoc=0.7.0=py35h296b98c_0
  - olefile=0.44=py35h1f523c6_0
  - openssl=1.0.2n=hdbc3d79_0
  - pandas=0.22.0=py35h0a44026_0
  - pandoc=1.19.2.1=ha5e8f32_1
  - pandocfilters=1.4.2=py35hff87490_1
  - parso=0.1.1=py35hbda7c10_0
  - partd=0.3.8=py35h6fadee7_0
  - patsy=0.5.0=py35_0
  - pcre=8.41=hfb6ab37_1
  - pexpect=4.3.1=py35_0
  - pickleshare=0.7.4=py35h9517181_0
  - pillow=4.2.1=py35_0
  - pip=9.0.1=py35h33ce766_4
  - prompt_toolkit=1.0.15=py35h93950c5_0
  - protobuf=3.4.1=py35h9d33684_0
  - psutil=5.4.3=py35h1de35cc_0
  - ptyprocess=0.5.2=py35hfc37984_0
  - pycodestyle=2.3.1=py35he0976b1_0
  - pycparser=2.18=py35hab820b0_1
  - pydot=1.2.3=py35h3a729fa_0
  - pydotplus=2.0.2=py35_0
  - pyflakes=1.6.0=py35hc517269_0
  - pygments=2.2.0=py35h392a662_0
  - pylint=1.8.1=py35_0
  - pyopenssl=17.5.0=py35h4065cf8_0
  - pyparsing=2.2.0=py35h31fab04_0
  - pyqt=5.6.0=py35hbd126f6_6
  - pysocks=1.6.7=py35h3cfcbe1_1
  - python=3.5.4=he720263_23
  - python-dateutil=2.6.1=py35h10515e0_1
  - python-graphviz=0.5.2=py35_0
  - python.app=2=py35he4d1c94_7
  - pytz=2017.3=py35heeb7564_0
  - pywavelets=0.5.2=py35h9dc8fb8_0
  - pyyaml=3.12=py35hf8cec8a_1
  - pyzmq=16.0.3=py35hab9903b_0
  - qt=5.6.2=h9975529_14
  - qtawesome=0.4.4=py35h21e61ad_0
  - qtconsole=4.3.1=py35hd6d667b_0
  - qtpy=1.3.1=py35h743f03e_0
  - readline=7.0=hc1231fa_4
  - requests=2.18.4=py35h0d65e6b_1
  - rope=0.10.7=py35h27868a4_0
  - scikit-image=0.13.1=py35h116c381_0
  - scikit-learn=0.19.1=py35h2b554eb_0
  - scipy=1.0.0=py35h8b35106_0
  - seaborn=0.8.1=py35he0bbe96_0
  - setuptools=38.4.0=py35_0
  - simplegeneric=0.8.1=py35h0a3d746_0
  - sip=4.18.1=py35h79e1f92_2
  - six=1.11.0=py35h39a4c60_1
  - snowballstemmer=1.2.1=py35hbb7be01_0
  - sortedcontainers=1.5.9=py35_0
  - sphinx=1.6.6=py35_0
  - sphinxcontrib=1.0=py35h3eabf46_1
  - sphinxcontrib-websupport=1.0.1=py35hcb4ca16_1
  - spyder=3.2.6=py35_0
  - sqlite=3.20.1=h7e4c145_2
  - statsmodels=0.8.0=py35ha7c9052_0
  - sympy=1.1.1=py35he478fab_0
  - tblib=1.3.2=py35h1b9c5fd_0
  - tensorflow=1.1.0=np112py35_0
  - testpath=0.3.1=py35hf8009f4_0
  - tk=8.6.7=h35a86e2_3
  - toolz=0.9.0=py35_0
  - tornado=4.5.3=py35_0
  - traitlets=4.3.2=py35hd3d1486_0
  - typing=3.6.2=py35ha402c5e_0
  - urllib3=1.22=py35he002d57_0
  - wcwidth=0.1.7=py35hdd0c235_0
  - webencodings=0.5.1=py35hcf8ebf9_1
  - werkzeug=0.14.1=py35_0
  - wheel=0.30.0=py35h5c0b906_1
  - wrapt=1.10.11=py35ha18cf31_0
  - xz=5.2.3=h0278029_2
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.2.2=ha360ad0_2
  - zict=0.1.3=py35h1ae85d2_0
  - zlib=1.2.11=hf3cbc9b_2
  - opencv3=3.1.0=py35_0
  - tbb=4.3_20141023=0
prefix: /Users/michaelarango/anaconda3/envs/HPSI-Classification

