name: HPSI-Classification
channels:
- conda-forge
- defaults
dependencies:
- bzip2=1.0.6=vc14_1
- ca-certificates=2017.11.5=0
- freetype=2.8.1=vc14_0
- h5py=2.7.1=py35_2
- hdf5=1.10.1=vc14_1
- icu=58.2=vc14_0
- jpeg=9b=vc14_2
- keras=2.0.9=py35_0
- libgpuarray=0.7.5=vc14_0
- libpng=1.6.34=vc14_0
- libtiff=4.0.9=vc14_0
- mako=1.0.7=py35_0
- markupsafe=1.0=py35_0
- openssl=1.0.2n=vc14_0
- pillow=5.0.0=py35_0
- protobuf=3.5.1=py35_vc14_3
- pygpu=0.7.5=py35_0
- pyyaml=3.12=py35_1
- qt=5.6.2=vc14_1
- theano=1.0.1=py35_1
- tk=8.5.19=vc14_1
- yaml=0.1.7=vc14_0
- zlib=1.2.11=vc14_0
- alabaster=0.7.10=py35_0
- astroid=1.5.3=py35_0
- babel=2.5.0=py35_0
- backports=1.0=py35_0
- backports.weakref=1.0rc1=py35_0
- bleach=1.5.0=py35_0
- certifi=2016.2.28=py35_0
- chardet=3.0.4=py35_0
- colorama=0.3.9=py35_0
- cycler=0.10.0=py35_0
- decorator=4.1.2=py35_0
- docutils=0.14=py35_0
- entrypoints=0.2.3=py35_0
- graphviz=2.38.0=4
- html5lib=0.9999999=py35_0
- imagesize=0.7.1=py35_0
- ipykernel=4.6.1=py35_0
- ipython=6.1.0=py35_0
- ipython_genutils=0.2.0=py35_0
- isort=4.2.15=py35_0
- jedi=0.10.2=py35_2
- jinja2=2.9.6=py35_0
- jsonschema=2.6.0=py35_0
- jupyter_client=5.1.0=py35_0
- jupyter_core=4.3.0=py35_0
- lazy-object-proxy=1.3.1=py35_0
- libprotobuf=3.2.0=vc14_0
- markdown=2.6.9=py35_0
- matplotlib=2.0.2=np113py35_0
- mistune=0.7.4=py35_0
- mkl=2017.0.3=0
- mpmath=0.19=py35_1
- nbconvert=5.2.1=py35_0
- nbformat=4.4.0=py35_0
- networkx=1.11=py35_0
- numpy=1.13.1=py35_0
- numpydoc=0.7.0=py35_0
- olefile=0.44=py35_0
- pandas=0.20.3=py35_0
- pandocfilters=1.4.2=py35_0
- path.py=10.3.1=py35_0
- patsy=0.4.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_1
- prompt_toolkit=1.0.15=py35_0
- psutil=5.2.2=py35_0
- pycodestyle=2.3.1=py35_0
- pydotplus=2.0.2=py35_0
- pyflakes=1.6.0=py35_0
- pygments=2.2.0=py35_0
- pylint=1.7.2=py35_0
- pyparsing=2.2.0=py35_0
- pyqt=5.6.0=py35_2
- python=3.5.4=0
- python-dateutil=2.6.1=py35_0
- python-graphviz=0.5.2=py35_0
- pytz=2017.2=py35_0
- pywavelets=0.5.2=np113py35_0
- pyzmq=16.0.2=py35_0
- qtawesome=0.4.4=py35_0
- qtconsole=4.3.1=py35_0
- qtpy=1.3.1=py35_0
- requests=2.14.2=py35_0
- rope=0.9.4=py35_1
- scikit-image=0.13.0=np113py35_0
- scikit-learn=0.19.0=np113py35_0
- scipy=0.19.1=np113py35_0
- seaborn=0.8=py35_0
- setuptools=36.4.0=py35_1
- simplegeneric=0.8.1=py35_1
- singledispatch=3.4.0.3=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_1
- snowballstemmer=1.2.1=py35_0
- sphinx=1.6.3=py35_0
- sphinxcontrib=1.0=py35_0
- sphinxcontrib-websupport=1.0.1=py35_0
- spyder=3.2.3=py35_0
- statsmodels=0.8.0=np113py35_0
- sympy=1.1.1=py35_0
- tensorflow=1.2.1=py35_0
- testpath=0.3.1=py35_0
- tornado=4.5.2=py35_0
- traitlets=4.3.2=py35_0
- vc=14=0
- vs2015_runtime=14.0.25420=0
- wcwidth=0.1.7=py35_0
- werkzeug=0.12.2=py35_0
- wheel=0.29.0=py35_0
- win_unicode_console=0.5=py35_0
- wincertstore=0.2=py35_0
- wrapt=1.10.11=py35_0
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15
  - pydot==1.2.4
  - rope-py3k==0.9.4.post1
  - win-unicode-console==0.5
prefix: C:\Users\User\Anaconda3\envs\HPSI-Classification

