name: HPSI-Classification
channels:
  - menpo
  - defaults
dependencies:
  - alabaster=0.7.10=py35h3a808de_0
  - asn1crypto=0.24.0=py35_0
  - astroid=1.6.0=py35_0
  - babel=2.5.3=py35_0
  - backports=1.0=py35he88aa47_1
  - backports.weakref=1.0rc1=py35_0
  - bleach=1.5.0=py35_0
  - bokeh=0.12.13=py35h047fa9f_0
  - ca-certificates=2017.08.26=h94faf87_0
  - certifi=2017.11.5=py35h456c6ae_0
  - cffi=1.11.4=py35hfa6e2cd_0
  - chardet=3.0.4=py35h177e1b7_1
  - click=6.7=py35h10df73f_0
  - cloudpickle=0.5.2=py35hd830302_0
  - colorama=0.3.9=py35h32a752f_0
  - cryptography=2.1.4=py35h8ead9e0_0
  - cycler=0.10.0=py35hcc71164_0
  - dask=0.16.1=py35_0
  - dask-core=0.16.1=py35_0
  - decorator=4.2.1=py35_0
  - distributed=1.20.2=py35_0
  - docutils=0.14=py35h8ccb97f_0
  - entrypoints=0.2.3=py35hb91ced9_2
  - fastcache=1.0.2=py35h8710e77_0
  - freetype=2.8=h51f8f2c_1
  - graphviz=2.38.0=4
  - h5py=2.7.1=py35hb2c3add_0
  - hdf5=1.10.1=h98b8871_1
  - heapdict=1.0.0=py35h3d1311d_0
  - html5lib=0.9999999=py35_0
  - icc_rt=2017.0.4=h97af966_0
  - icu=58.2=ha66f8fd_1
  - idna=2.6=py35h8dcb9ae_1
  - imageio=2.2.0=py35hcd4b9a4_0
  - imagesize=0.7.1=py35h7f87e83_0
  - intel-openmp=2018.0.0=hd92c6cd_8
  - ipykernel=4.7.0=py35h2f9c1c0_0
  - ipython=6.2.1=py35h4a2ac14_1
  - ipython_genutils=0.2.0=py35ha709e79_0
  - isort=4.2.15=py35h0bf7b49_0
  - jedi=0.11.1=py35_0
  - jinja2=2.10=py35hdf652bb_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=2.6.0=py35h27d56d3_0
  - jupyter_client=5.2.1=py35_0
  - jupyter_core=4.4.0=py35h629ba7f_0
  - keras=2.1.2=py35_0
  - lazy-object-proxy=1.3.1=py35he996729_0
  - libpng=1.6.32=h140d38e_4
  - libprotobuf=3.4.1=h3dba5dd_0
  - libtiff=4.0.9=h0f13578_0
  - locket=0.2.0=py35h0dfcdd0_1
  - markdown=2.6.9=py35_0
  - markupsafe=1.0=py35hc253e08_1
  - matplotlib=2.1.1=py35h2062329_0
  - mccabe=0.6.1=py35hcf31250_1
  - mistune=0.8.3=py35_0
  - mkl=2018.0.1=h2108138_4
  - mpmath=1.0.0=py35h253b693_2
  - msgpack-python=0.5.1=py35he980bc4_0
  - nbconvert=5.3.1=py35h98d6c46_0
  - nbformat=4.4.0=py35h908c9d9_0
  - networkx=2.0=py35h29b0c50_0
  - numpy=1.14.0=py35h4a99626_0
  - numpydoc=0.7.0=py35h72ac4f2_0
  - olefile=0.44=py35h7ba86d0_0
  - openssl=1.0.2n=h74b6da3_0
  - pandas=0.22.0=py35h6538335_0
  - pandoc=1.19.2.1=hb2460c7_1
  - pandocfilters=1.4.2=py35h978f723_1
  - parso=0.1.1=py35he39c48a_0
  - partd=0.3.8=py35h894d1e4_0
  - patsy=0.5.0=py35_0
  - pickleshare=0.7.4=py35h2f9f535_0
  - pillow=5.0.0=py35h0738816_0
  - pip=9.0.1=py35h691316f_4
  - prompt_toolkit=1.0.15=py35h89c7cb4_0
  - protobuf=3.4.1=py35h58370bd_0
  - psutil=5.4.3=py35hfa6e2cd_0
  - pycodestyle=2.3.1=py35h35694a3_0
  - pycparser=2.18=py35h15a15da_1
  - pydot=1.2.3=py35hd159ffb_0
  - pydotplus=2.0.2=py35_0
  - pyflakes=1.6.0=py35hb7fdafe_0
  - pygments=2.2.0=py35h24c0941_0
  - pylint=1.8.1=py35_0
  - pyopenssl=17.5.0=py35h75c5b16_0
  - pyparsing=2.2.0=py35hcabcaab_1
  - pyqt=5.6.0=py35hd46907b_5
  - pysocks=1.6.7=py35hb30ac0d_1
  - python=3.5.4=h1357f44_23
  - python-dateutil=2.6.1=py35h6b299a3_1
  - python-graphviz=0.5.2=py35_0
  - pytz=2017.3=py35hb294b1a_0
  - pywavelets=0.5.2=py35h7c47ace_0
  - pyyaml=3.12=py35h4bf9689_1
  - pyzmq=16.0.3=py35h1861011_0
  - qt=5.6.2=vc14h6f8c307_12
  - qtawesome=0.4.4=py35h639d0ff_0
  - qtconsole=4.3.1=py35hc47b0dd_0
  - qtpy=1.3.1=py35h4918c39_0
  - requests=2.18.4=py35h54a615f_1
  - rope=0.10.7=py35h5756fe0_0
  - scikit-image=0.13.1=py35hfa6e2cd_1
  - scikit-learn=0.19.1=py35h2037775_0
  - scipy=1.0.0=py35h75710e8_0
  - seaborn=0.8.1=py35hc73483e_0
  - setuptools=38.4.0=py35_0
  - simplegeneric=0.8.1=py35h6406082_0
  - sip=4.18.1=py35h01cbaa7_2
  - six=1.11.0=py35hc1da2df_1
  - snowballstemmer=1.2.1=py35h4c55bfa_0
  - sortedcontainers=1.5.9=py35_0
  - sphinx=1.6.6=py35_0
  - sphinxcontrib=1.0=py35h45f5ca3_1
  - sphinxcontrib-websupport=1.0.1=py35ha3690eb_1
  - spyder=3.2.6=py35_0
  - sqlite=3.20.1=h9eeafa9_2
  - statsmodels=0.8.0=py35hfa6034c_0
  - sympy=1.1.1=py35ha5375ed_0
  - tblib=1.3.2=py35hd2cf7e1_0
  - tensorflow=1.2.1=py35_0
  - testpath=0.3.1=py35h06cf69e_0
  - tk=8.6.7=hcb92d03_3
  - toolz=0.9.0=py35_0
  - tornado=4.5.3=py35_0
  - traitlets=4.3.2=py35h09b975b_0
  - typing=3.6.2=py35h37628ea_0
  - urllib3=1.22=py35h8cc84eb_0
  - vc=14=h0510ff6_3
  - vs2015_runtime=14.0.25420=0
  - wcwidth=0.1.7=py35h6e80d8a_0
  - werkzeug=0.14.1=py35_0
  - wheel=0.30.0=py35h38a90bc_1
  - win_inet_pton=1.0.1=py35hbef1270_1
  - win_unicode_console=0.5=py35h56988b5_0
  - wincertstore=0.2=py35hfebbdb8_0
  - wrapt=1.10.11=py35h54666f7_0
  - yaml=0.1.7=hc54c509_2
  - zict=0.1.3=py35hf5542e0_0
  - zlib=1.2.11=h8395fce_2
  - opencv3=3.1.0=py35_0
prefix: C:\Users\Amir\AppData\Local\conda\conda\envs\HPSI-Classification

